config:
  target: https://f3wjgtrbeh.execute-api.eu-west-1.amazonaws.com/v1/
  phases:
    - duration: 10
      arrivalRate: 10
      name: benchmarking

scenarios:
  - name: requestAuthorizerPython
    flow:
      - get:
          url: /req-auth-python?QueryString1=queryValue1
          expect:
            - statusCode: 200
