config:
  target: https://f3wjgtrbeh.execute-api.eu-west-1.amazonaws.com/v1/
  phases:
    - duration: 10
      arrivalRate: 10
      name: benchmarking

scenarios:
  - name: tokenAuthorizerPython
    flow:
      - get:
          url: /tkn-auth-python
          headers:
            AuthorizationToken: "Bearer allow"
          expect:
            - statusCode: 200
